# 项目相关配置
SiWu:
  # 名称
  name: SiWu-IoT
  # 版本
  version: 3.8.8
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置 D:/A-SiWu-IoT/uploadPath，Linux配置 /www/JavaProject/A-SiWu-IoT/uploadPath）
  profile: /www/wwwroot/JavaProject/A-SiWu-IoT/uploadPath
#  profile:  D:/A-SiWu-IoT/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
# 大屏配置

gc:
  starter:
    file:
      # 一个存储文件的绝对路径，需要有写入权限，这里可以直接引用SiWu的配置
      basePath: ${SiWu.profile}
#      basePath: /www/wwwroot/JavaProject/A-SiWu-IoT/uploadPath
      # 静态资源访问接口前缀
      urlPrefix: http://127.0.0.1:${server.port}${server.servlet.context-path}static/
#      urlPrefix: http://bs.jinhuwl.top/prod-api/static/
#      urlPrefix: https://sv.jinhuwl.top:5743/prod-api/static/

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9712
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.swiot: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: ali
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

  resources:
    # 自springboot 2.5.5之后，该属性已经被废弃，使用web.resources.static-locations代替
    static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/,file:${gc.starter.file.basePath}
  mvc:
    throw-exception-if-no-handler-found: true
    # 静态资源访问接口前缀
    static-path-pattern: /static/**

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 300000
jackson:
  time-zone: GMT+8
  date-format: yyyy-MM-dd HH:mm:ss
  deserialization:
    # 当实体中没有属性的setter方法时是否抛出异常
    FAIL_ON_UNKNOWN_PROPERTIES: false
    # 字符串转允许List，否则导致 @RequestBody List<T> list 类型无法解析
    ACCEPT_SINGLE_VALUE_AS_ARRAY: true

# MyBatis Plus配置
mybatis-plus:
  # Mapper.xml 文件位置 Maven 多模块项目的扫描路径需以 classpath*: 开头
  mapper-locations: classpath*:mapper/**/*.xml
  #  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.swiot.**.domain
  checkConfigLocation : true
  configuration: # MyBatis 原生支持的配置
    # 是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config: # 全局策略配置
    # 是否控制台 print mybatis-plus 的 LOGO
    banner: true
    db-config:
      # id类型
      id-type: auto
      # 表名是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: true
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: false
  # 请求前缀
  pathMapping: /sw-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*




